import house1 from "../assets/img/house1.jpg";
import house2 from "../assets/img/house2.jpg";
import house3 from "../assets/img/house3.jpg";
import house4 from "../assets/img/house4.jpg";
import house5 from "../assets/img/house5.jpg";
import house6 from "../assets/img/house6.jpg";
import flat1 from "../assets/img/flat1.jpeg";
import flat2 from "../assets/img/flat2.jpg";
import flat3 from "../assets/img/flat3.jpg";
import flat4 from "../assets/img/flat4.jpg";

export const cardData = [
  {
    id: 1,
    img: house1,
    price: 20000,
    type: "House",
    location: "Mumbai",
    date: "",
    name: "Sainath Estate Agency",
    add: "Sector 10,Sanpada, Mumbai",
    bed: "2 Beds",
    bathroom: "3 Bathrooms",
    area: "1000 sq.ft",
    fav: false,
    popular: false,
  },
  {
    id: 2,
    img: house2,
    price: 30000,
    name: "Skyline Realtor",
    add: "Khargar, Mumbai",
    type: "House",
    location: "Mumbai",
    date: "",
    bed: "4 Bed",
    bathroom: "2 Bathrooms",
    area: "2000 sq.ft",
    fav: false,
    popular: true,
  },
  {
    id: 3,
    img: house3,
    price: 15000,
    name: "Om Sai Real estate",
    add: "Koperkhairane, Mumbai",
    type: "House",
    location: "Mumbai",
    date: "",
    bed: "1 Beds",
    bathroom: "2 Bathrooms",
    area: "500 sq.ft",
    fav: false,
    popular: false,
  },
  {
    id: 4,
    img: house4,
    price: 15000,
    type: "House",
    location: "Bangalore",
    date: "",
    name: "Chimney Hills View",
    add: "Kirloskar Layout, Bangalore",
    bed: "2 Bed",
    bathroom: "1 Bathroom",
    area: "800 sq.ft",
    fav: false,
    popular: false,
  },
  {
    id: 5,
    img: house5,
    price: 20000,
    type: "House",
    location: "Bangalore",
    date: "",
    name: "Nestaway",
    add: "Basaveshwara Nagar, Bangalore",
    bed: "2 Bed",
    bathroom: "2 Bathroom",
    area: "1200 sq.ft",
    fav: false,
    popular: false,
  },
  {
    id: 6,
    img: house6,
    price: 30000,
    type: "House",
    location: "Bangalore",
    date: "",
    name: "SVR realty",
    add: "Whitefield outer circle, Bangalore",
    bed: "3 Bed",
    bathroom: "3 Bathroom",
    area: "2000 sq.ft",
    fav: false,
    popular: true,
  },
  {
    id: 7,
    img: flat1,
    price: 18000,
    type: "Flat",
    location: "Bangalore",
    date: "",
    name: "RKM Residency",
    add: "Hebbal Kempapura, Bangalore",
    bed: "2 Bedroom",
    bathroom: "2 Bathroom",
    area: "1000 sq.ft",
    fav: false,
    popular: false,
  },
  {
    id: 8,
    img: flat2,
    price: 30000,
    type: "Flat",
    location: "Bangalore",
    date: "",
    name: "Sobha Classic",
    add: "Harlur, Bangalore",
    bed: "3 Bed",
    bathroom: "3 Bathroom",
    area: "2000 sq.ft",
    fav: false,
    popular: true,
  },
  {
    id: 9,
    img: flat3,
    price: 18000,
    type: "Flat",
    location: "Mumbai",
    date: "",
    name: "Prathmesh Paradise",
    add: "Kalyan(East), Mumbai",
    bed: "2 Bed",
    bathroom: "2 Bathroom",
    area: "1200 sq.ft",
    fav: false,
    popular: false,
  },
  {
    id: 10,
    img: flat4,
    price: 30000,
    type: "Flat",
    location: "Mumbai",
    date: "",
    name: "Uma Sparta",
    add: "Hiranandani Estate, Mumbai",
    bed: "3 Bed",
    bathroom: "3 Bathroom",
    area: "2000 sq.ft",
    fav: false,
    popular: true,
  },
];
